name: C++ CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++

    - name: Create build directory
      run: mkdir -p cpp_bestia/build

    - name: Run CMake
      run: cmake ..
      working-directory: cpp_bestia/build

    - name: Build with CMake
      run: cmake --build .
      working-directory: cpp_bestia/build

    - name: Verify build
      run: make
      working-directory: cpp_bestia/build
